(ns translations.es
  (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def
  translations
  {"|Ping the server!"                                   "¡Ping el servidor!",
   "|The meaning of life is {meaning}."                  "El significado de la vida es {meaning}.",
   "|Ask Deep Thought server about the meaning of life." "Pensé acerca del significado de su pintura."
   "|(Deep Thought Hums)"                                "(Deep Thought tararea)"})

(swap! fulcro.i18n/*loaded-translations* assoc "es" translations)